// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/v1/goethe.proto

package spec

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cursor struct {
	Topic                *Topic   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Consumer             string   `protobuf:"bytes,2,opt,name=consumer,proto3" json:"consumer,omitempty"`
	CurrentEvent         *Event   `protobuf:"bytes,3,opt,name=current_event,json=currentEvent,proto3" json:"current_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cursor) Reset()         { *m = Cursor{} }
func (m *Cursor) String() string { return proto.CompactTextString(m) }
func (*Cursor) ProtoMessage()    {}
func (*Cursor) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e567c1cdd9caf08, []int{0}
}

func (m *Cursor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cursor.Unmarshal(m, b)
}
func (m *Cursor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cursor.Marshal(b, m, deterministic)
}
func (m *Cursor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cursor.Merge(m, src)
}
func (m *Cursor) XXX_Size() int {
	return xxx_messageInfo_Cursor.Size(m)
}
func (m *Cursor) XXX_DiscardUnknown() {
	xxx_messageInfo_Cursor.DiscardUnknown(m)
}

var xxx_messageInfo_Cursor proto.InternalMessageInfo

func (m *Cursor) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Cursor) GetConsumer() string {
	if m != nil {
		return m.Consumer
	}
	return ""
}

func (m *Cursor) GetCurrentEvent() *Event {
	if m != nil {
		return m.CurrentEvent
	}
	return nil
}

type Event struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic                *Topic   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e567c1cdd9caf08, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *Event) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Topic struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e567c1cdd9caf08, []int{2}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Cursor)(nil), "io.typusomega.goethe.Cursor")
	proto.RegisterType((*Event)(nil), "io.typusomega.goethe.Event")
	proto.RegisterType((*Topic)(nil), "io.typusomega.goethe.Topic")
}

func init() { proto.RegisterFile("protos/v1/goethe.proto", fileDescriptor_1e567c1cdd9caf08) }

var fileDescriptor_1e567c1cdd9caf08 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x3b, 0x91, 0x24, 0xf6, 0x5a, 0x5d, 0x0c, 0xa2, 0x21, 0xba, 0x28, 0x01, 0x31, 0xab,
	0x89, 0xad, 0x2f, 0x20, 0x96, 0xe2, 0xc2, 0x8d, 0x04, 0x57, 0x6e, 0x24, 0x9d, 0x0c, 0x69, 0xd0,
	0xe4, 0x0e, 0xf3, 0x53, 0xe8, 0xa3, 0x08, 0x3e, 0xac, 0x74, 0x52, 0x2d, 0x48, 0x09, 0xdd, 0xcd,
	0x99, 0xf3, 0xdd, 0x3b, 0x87, 0x39, 0x70, 0x21, 0x15, 0x1a, 0xd4, 0xd9, 0x6a, 0x92, 0x55, 0x28,
	0xcc, 0x52, 0x30, 0x77, 0x41, 0xcf, 0x6b, 0x64, 0x66, 0x2d, 0xad, 0xc6, 0x46, 0x54, 0x05, 0xeb,
	0xbc, 0xe4, 0x8b, 0x40, 0x30, 0xb3, 0x4a, 0xa3, 0xa2, 0x13, 0xf0, 0x0d, 0xca, 0x9a, 0x47, 0x64,
	0x4c, 0xd2, 0x93, 0xe9, 0x15, 0xdb, 0x37, 0xc0, 0x5e, 0x37, 0x48, 0xde, 0x91, 0x34, 0x86, 0x63,
	0x8e, 0xad, 0xb6, 0x8d, 0x50, 0x91, 0x37, 0x26, 0xe9, 0x30, 0xff, 0xd3, 0xf4, 0x01, 0x4e, 0xb9,
	0x55, 0x4a, 0xb4, 0xe6, 0x5d, 0xac, 0x44, 0x6b, 0xa2, 0xa3, 0xbe, 0xb5, 0xf3, 0x0d, 0x92, 0x8f,
	0xb6, 0x13, 0x4e, 0x25, 0x25, 0xf8, 0xee, 0x40, 0xcf, 0xc0, 0xab, 0x4b, 0x17, 0x6b, 0x98, 0x7b,
	0x75, 0xb9, 0x4b, 0xea, 0x1d, 0x9c, 0x34, 0x82, 0x50, 0x16, 0xeb, 0x4f, 0x2c, 0x4a, 0x97, 0x63,
	0x94, 0xff, 0xca, 0xe4, 0x12, 0x7c, 0x47, 0xfe, 0x7f, 0x65, 0xfa, 0x4d, 0x20, 0x78, 0x72, 0xab,
	0xe8, 0x1c, 0xc2, 0x17, 0x85, 0xa5, 0xe5, 0x82, 0xf6, 0xe5, 0x8f, 0xfb, 0xcc, 0x64, 0x40, 0x9f,
	0x21, 0x9c, 0x75, 0xdf, 0x43, 0xaf, 0xf7, 0x93, 0x5d, 0x15, 0x71, 0xaf, 0x9b, 0x0c, 0x52, 0x72,
	0x47, 0x1e, 0x6f, 0xdf, 0x6e, 0xaa, 0xda, 0x2c, 0xed, 0x82, 0x71, 0x6c, 0xb2, 0x1d, 0xbc, 0x6d,
	0x3d, 0x93, 0x1f, 0x55, 0xa6, 0xa5, 0xe0, 0x8b, 0xc0, 0xf5, 0x7f, 0xff, 0x13, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0x0a, 0x58, 0xdc, 0x19, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoetheClient is the client API for Goethe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoetheClient interface {
	Produce(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
	Consume(ctx context.Context, opts ...grpc.CallOption) (Goethe_ConsumeClient, error)
}

type goetheClient struct {
	cc *grpc.ClientConn
}

func NewGoetheClient(cc *grpc.ClientConn) GoetheClient {
	return &goetheClient{cc}
}

func (c *goetheClient) Produce(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/io.typusomega.goethe.Goethe/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goetheClient) Consume(ctx context.Context, opts ...grpc.CallOption) (Goethe_ConsumeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Goethe_serviceDesc.Streams[0], "/io.typusomega.goethe.Goethe/Consume", opts...)
	if err != nil {
		return nil, err
	}
	x := &goetheConsumeClient{stream}
	return x, nil
}

type Goethe_ConsumeClient interface {
	Send(*Cursor) error
	Recv() (*Cursor, error)
	grpc.ClientStream
}

type goetheConsumeClient struct {
	grpc.ClientStream
}

func (x *goetheConsumeClient) Send(m *Cursor) error {
	return x.ClientStream.SendMsg(m)
}

func (x *goetheConsumeClient) Recv() (*Cursor, error) {
	m := new(Cursor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GoetheServer is the server API for Goethe service.
type GoetheServer interface {
	Produce(context.Context, *Event) (*Event, error)
	Consume(Goethe_ConsumeServer) error
}

// UnimplementedGoetheServer can be embedded to have forward compatible implementations.
type UnimplementedGoetheServer struct {
}

func (*UnimplementedGoetheServer) Produce(ctx context.Context, req *Event) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (*UnimplementedGoetheServer) Consume(srv Goethe_ConsumeServer) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}

func RegisterGoetheServer(s *grpc.Server, srv GoetheServer) {
	s.RegisterService(&_Goethe_serviceDesc, srv)
}

func _Goethe_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoetheServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.typusomega.goethe.Goethe/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoetheServer).Produce(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Goethe_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoetheServer).Consume(&goetheConsumeServer{stream})
}

type Goethe_ConsumeServer interface {
	Send(*Cursor) error
	Recv() (*Cursor, error)
	grpc.ServerStream
}

type goetheConsumeServer struct {
	grpc.ServerStream
}

func (x *goetheConsumeServer) Send(m *Cursor) error {
	return x.ServerStream.SendMsg(m)
}

func (x *goetheConsumeServer) Recv() (*Cursor, error) {
	m := new(Cursor)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Goethe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.typusomega.goethe.Goethe",
	HandlerType: (*GoetheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Goethe_Produce_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _Goethe_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protos/v1/goethe.proto",
}
