// Code generated by protoc-gen-go. DO NOT EDIT.
// source: raft.proto

package spec

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RaftLog struct {
	// Types that are valid to be assigned to Event:
	//	*RaftLog_CursorMoved
	//	*RaftLog_EventProduced
	Event                isRaftLog_Event `protobuf_oneof:"event"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RaftLog) Reset()         { *m = RaftLog{} }
func (m *RaftLog) String() string { return proto.CompactTextString(m) }
func (*RaftLog) ProtoMessage()    {}
func (*RaftLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{0}
}

func (m *RaftLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RaftLog.Unmarshal(m, b)
}
func (m *RaftLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RaftLog.Marshal(b, m, deterministic)
}
func (m *RaftLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RaftLog.Merge(m, src)
}
func (m *RaftLog) XXX_Size() int {
	return xxx_messageInfo_RaftLog.Size(m)
}
func (m *RaftLog) XXX_DiscardUnknown() {
	xxx_messageInfo_RaftLog.DiscardUnknown(m)
}

var xxx_messageInfo_RaftLog proto.InternalMessageInfo

type isRaftLog_Event interface {
	isRaftLog_Event()
}

type RaftLog_CursorMoved struct {
	CursorMoved *CursorMoved `protobuf:"bytes,2,opt,name=cursor_moved,json=cursorMoved,proto3,oneof"`
}

type RaftLog_EventProduced struct {
	EventProduced *EventProduced `protobuf:"bytes,3,opt,name=event_produced,json=eventProduced,proto3,oneof"`
}

func (*RaftLog_CursorMoved) isRaftLog_Event() {}

func (*RaftLog_EventProduced) isRaftLog_Event() {}

func (m *RaftLog) GetEvent() isRaftLog_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *RaftLog) GetCursorMoved() *CursorMoved {
	if x, ok := m.GetEvent().(*RaftLog_CursorMoved); ok {
		return x.CursorMoved
	}
	return nil
}

func (m *RaftLog) GetEventProduced() *EventProduced {
	if x, ok := m.GetEvent().(*RaftLog_EventProduced); ok {
		return x.EventProduced
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RaftLog) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RaftLog_CursorMoved)(nil),
		(*RaftLog_EventProduced)(nil),
	}
}

type JoinRequest struct {
	NodeAddress          string   `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	NodePort             int32    `protobuf:"varint,2,opt,name=node_port,json=nodePort,proto3" json:"node_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{1}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *JoinRequest) GetNodePort() int32 {
	if m != nil {
		return m.NodePort
	}
	return 0
}

type EventProduced struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventProduced) Reset()         { *m = EventProduced{} }
func (m *EventProduced) String() string { return proto.CompactTextString(m) }
func (*EventProduced) ProtoMessage()    {}
func (*EventProduced) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{2}
}

func (m *EventProduced) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventProduced.Unmarshal(m, b)
}
func (m *EventProduced) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventProduced.Marshal(b, m, deterministic)
}
func (m *EventProduced) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventProduced.Merge(m, src)
}
func (m *EventProduced) XXX_Size() int {
	return xxx_messageInfo_EventProduced.Size(m)
}
func (m *EventProduced) XXX_DiscardUnknown() {
	xxx_messageInfo_EventProduced.DiscardUnknown(m)
}

var xxx_messageInfo_EventProduced proto.InternalMessageInfo

func (m *EventProduced) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type CursorMoved struct {
	Cursor               *Cursor  `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CursorMoved) Reset()         { *m = CursorMoved{} }
func (m *CursorMoved) String() string { return proto.CompactTextString(m) }
func (*CursorMoved) ProtoMessage()    {}
func (*CursorMoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_b042552c306ae59b, []int{3}
}

func (m *CursorMoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CursorMoved.Unmarshal(m, b)
}
func (m *CursorMoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CursorMoved.Marshal(b, m, deterministic)
}
func (m *CursorMoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CursorMoved.Merge(m, src)
}
func (m *CursorMoved) XXX_Size() int {
	return xxx_messageInfo_CursorMoved.Size(m)
}
func (m *CursorMoved) XXX_DiscardUnknown() {
	xxx_messageInfo_CursorMoved.DiscardUnknown(m)
}

var xxx_messageInfo_CursorMoved proto.InternalMessageInfo

func (m *CursorMoved) GetCursor() *Cursor {
	if m != nil {
		return m.Cursor
	}
	return nil
}

func init() {
	proto.RegisterType((*RaftLog)(nil), "io.typusomega.goethe.RaftLog")
	proto.RegisterType((*JoinRequest)(nil), "io.typusomega.goethe.JoinRequest")
	proto.RegisterType((*EventProduced)(nil), "io.typusomega.goethe.EventProduced")
	proto.RegisterType((*CursorMoved)(nil), "io.typusomega.goethe.CursorMoved")
}

func init() { proto.RegisterFile("raft.proto", fileDescriptor_b042552c306ae59b) }

var fileDescriptor_b042552c306ae59b = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x6b, 0xea, 0x40,
	0x14, 0xc5, 0xcd, 0x7b, 0xfe, 0x79, 0xde, 0xe8, 0x5b, 0x0c, 0x8f, 0x87, 0x68, 0x17, 0x9a, 0x52,
	0xea, 0x6a, 0x42, 0x6d, 0xbf, 0x40, 0x15, 0x8b, 0xb4, 0x0a, 0x32, 0xcb, 0x6e, 0x24, 0x7f, 0xae,
	0x31, 0xd4, 0x78, 0xa7, 0x93, 0x89, 0xe0, 0x37, 0xea, 0xc7, 0x2c, 0x99, 0xa4, 0x68, 0xc1, 0xba,
	0x9c, 0xc3, 0x6f, 0xce, 0xbd, 0xf7, 0x1c, 0x00, 0xe5, 0xad, 0x35, 0x97, 0x8a, 0x34, 0xb1, 0x7f,
	0x31, 0x71, 0x7d, 0x90, 0x59, 0x4a, 0x09, 0x46, 0x1e, 0x8f, 0x08, 0xf5, 0x06, 0xbb, 0xbd, 0x88,
	0x28, 0xda, 0xa2, 0x6b, 0x18, 0x3f, 0x5b, 0xbb, 0x98, 0x48, 0x7d, 0x28, 0xbe, 0x74, 0x5b, 0x32,
	0xf3, 0xb7, 0x71, 0x50, 0xbc, 0x9c, 0x0f, 0x0b, 0x1a, 0xc2, 0x5b, 0xeb, 0x39, 0x45, 0xec, 0x09,
	0x5a, 0x41, 0xa6, 0x52, 0x52, 0xab, 0x84, 0xf6, 0x18, 0x76, 0x7e, 0xf5, 0xad, 0xa1, 0x3d, 0x1a,
	0xf0, 0x73, 0x33, 0xf8, 0xc4, 0x90, 0x8b, 0x1c, 0x9c, 0x55, 0x84, 0x1d, 0x1c, 0x9f, 0x6c, 0x0e,
	0x7f, 0x71, 0x8f, 0x3b, 0xbd, 0x92, 0x8a, 0xc2, 0x2c, 0xc0, 0xb0, 0xf3, 0xdb, 0x38, 0x5d, 0x9f,
	0x77, 0x9a, 0xe6, 0xec, 0xb2, 0x44, 0x67, 0x15, 0xd1, 0xc6, 0x53, 0x61, 0xdc, 0x80, 0x9a, 0x11,
	0x9c, 0x05, 0xd8, 0xcf, 0x14, 0xef, 0x04, 0xbe, 0x67, 0x98, 0x6a, 0x36, 0x80, 0xd6, 0x8e, 0x42,
	0x5c, 0x79, 0x61, 0xa8, 0x30, 0x4d, 0x3b, 0x56, 0xdf, 0x1a, 0x36, 0x85, 0x9d, 0x6b, 0x8f, 0x85,
	0xc4, 0x7a, 0xd0, 0x34, 0x88, 0x24, 0xa5, 0xcd, 0x35, 0x35, 0xf1, 0x27, 0x17, 0x96, 0xa4, 0xb4,
	0x33, 0x86, 0xf6, 0xb7, 0xc9, 0xec, 0xae, 0x1c, 0x64, 0x9c, 0xec, 0x51, 0xef, 0xc2, 0xb6, 0xa2,
	0x5c, 0x69, 0x02, 0xf6, 0x49, 0x0e, 0xec, 0x01, 0xea, 0x45, 0x0e, 0xa5, 0xc5, 0xd5, 0xa5, 0xe8,
	0x44, 0xc9, 0x8e, 0x5e, 0xa0, 0x9a, 0x37, 0xc0, 0x26, 0x50, 0xcd, 0xef, 0x63, 0x3f, 0x04, 0x7e,
	0x72, 0x7b, 0xf7, 0x3f, 0x2f, 0x1a, 0xe6, 0x5f, 0x0d, 0xf3, 0x69, 0xde, 0xb0, 0x53, 0x19, 0xdf,
	0xbe, 0xde, 0x44, 0xb1, 0xde, 0x64, 0x3e, 0x0f, 0x28, 0x71, 0x8f, 0x2e, 0x6e, 0xe1, 0xe2, 0xca,
	0xb7, 0xc8, 0x4d, 0x25, 0x06, 0x7e, 0xdd, 0x7c, 0xbd, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xb2,
	0x34, 0x4b, 0x44, 0x4e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RaftClient is the client API for Raft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RaftClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type raftClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftClient(cc grpc.ClientConnInterface) RaftClient {
	return &raftClient{cc}
}

func (c *raftClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/io.typusomega.goethe.Raft/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftServer is the server API for Raft service.
type RaftServer interface {
	Join(context.Context, *JoinRequest) (*empty.Empty, error)
}

// UnimplementedRaftServer can be embedded to have forward compatible implementations.
type UnimplementedRaftServer struct {
}

func (*UnimplementedRaftServer) Join(ctx context.Context, req *JoinRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}

func RegisterRaftServer(s *grpc.Server, srv RaftServer) {
	s.RegisterService(&_Raft_serviceDesc, srv)
}

func _Raft_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.typusomega.goethe.Raft/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Raft_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.typusomega.goethe.Raft",
	HandlerType: (*RaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Raft_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "raft.proto",
}
