// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/typusomega/goethe/pkg/storage (interfaces: EventsIterator)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	spec "github.com/typusomega/goethe/pkg/spec"
)

// MockEventsIterator is a mock of EventsIterator interface
type MockEventsIterator struct {
	ctrl     *gomock.Controller
	recorder *MockEventsIteratorMockRecorder
}

// MockEventsIteratorMockRecorder is the mock recorder for MockEventsIterator
type MockEventsIteratorMockRecorder struct {
	mock *MockEventsIterator
}

// NewMockEventsIterator creates a new mock instance
func NewMockEventsIterator(ctrl *gomock.Controller) *MockEventsIterator {
	mock := &MockEventsIterator{ctrl: ctrl}
	mock.recorder = &MockEventsIteratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEventsIterator) EXPECT() *MockEventsIteratorMockRecorder {
	return m.recorder
}

// Close mocks base method
func (m *MockEventsIterator) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close
func (mr *MockEventsIteratorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventsIterator)(nil).Close))
}

// Next mocks base method
func (m *MockEventsIterator) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next
func (mr *MockEventsIteratorMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockEventsIterator)(nil).Next))
}

// Value mocks base method
func (m *MockEventsIterator) Value() (*spec.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].(*spec.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Value indicates an expected call of Value
func (mr *MockEventsIteratorMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockEventsIterator)(nil).Value))
}
